[package]
build = "build.rs"
edition = "2021"
name = "distributed_handlers"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor = "0.2.0"
libc-print = "0.1.21"
